version: '3.7'
# pw services composer file
services:
  # Database service
  db:
    image: mariadb:10.5.5
    container_name: dev-pw-db
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mariadb:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=docker
    networks:
      # we connect db service to an alternative network to isolate db manager from API service
      - pw-db
  # Database web panel
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev-pw-phpmyadmin
    restart: unless-stopped
    links:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST="db"
      - MYSQL_ROOT_PASSWORD="docker"
    ports:
      - '8080:80'
    networks:
      - pw-db
networks:
  pw-db:
volumes:
  db-data:
